trigger:
  branches:
    include:
      - main
      - master

variables:
  imageName: 'registryfiap.azurecr.io/users-api'
  acrName: 'registryfiap.azurecr.io'
  tag: '$(Build.BuildId)'
  dockerfilePath: 'src/Dockerfile'
  buildContext: 'src'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push Image to ACR'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Login no Azure Container Registry'
      inputs:
        command: login
        containerRegistry: 'AzureContainerRegistryServiceConnection' 

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        repository: '$(imageName)'
        command: build
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(buildContext)'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        repository: '$(imageName)'
        command: push
        tags: |
          $(tag)
          latest
